public class Conversor {

    		public decimal metrosParaCentimetros(decimal metros){
        		return metros*100;
    		}
    
    		public decimal centimetrosParaMetros(decimal centimetros){
        		return centimetros/100;
    		}
    
    		public decimal realParaDolar(decimal real){
        		return real/5.28;
    		}
    
    		public decimal dolarParaReal(decimal dolar){
        		return dolar*5.28;
    		}
    
    		public decimal pesParaCentimetros(decimal pes){
        		return pes*30.48;
    		}
    
    		public decimal centimetrosParaPes(decimal centimentros){
        		return centimentros/30.48;
    		}
    
		public decimal realParaEuro(decimal real){
        		return real/5.57;
    		}
                        
		public decimal euroParaReal(decimal euro){
        		return euro*5.57;
    		}
    
    		public decimal ieneParaReal(decimal iene){
        		return iene*0.04;
    		}
    
    		public Double realParaIene(decimal real){
        		return real/0.04;
    		}
    
	}